### ISSUE TITLE
最新版无法运行

### ISSUE THREAD

**Issue by hseermc** [GuizhanCraft/FastMachines#50]
### 检查项目

- [X] 你使用的是从鬼斩构建站（<https://builds.guizhanss.com>）或 Blob 构建站（<https://blob.build/>）下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/ybw0014/FastMachines/issues)，且没有找到相同的问题

### 问题描述

出现报错
[22:23:21] [Server thread/INFO]: [FastMachines] Enabling FastMachines vBuild 40 (git 1e15fda)
[22:23:21] [Server thread/ERROR]: Error occurred while enabling FastMachines vBuild 40 (git 1e15fda) (Is it up to date?)
java.lang.NoClassDefFoundError: net/guizhanss/fastmachines/libs/guizhanlibplugin/updater/GuizhanUpdater
	at FastMachines-Build 40 (git 1e15fda).jar/net.guizhanss.fastmachines.FastMachines.autoUpdate(FastMachines.java:140) ~[FastMachines-Build 40 (git 1e15fda).jar:?]
	at FastMachines-Build 40 (git 1e15fda).jar/net.guizhanss.fastmachines.libs.guizhanlib.slimefun.addon.AbstractAddon.onEnable(AbstractAddon.java:319) ~[FastMachines-Build 40 (git 1e15fda).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:633) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:582) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:751) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:510) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[leaves-1.21.jar:1.21-12-ab8b5f9]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.guizhanss.fastmachines.libs.guizhanlibplugin.updater.GuizhanUpdater
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 14 more

### 复现步骤

下载build 40，然后开机自动禁用

### 预期行为

正常加载

### 服务端软件

Paper

### Minecraft 版本

1.21

### Slimefun版本

Slimefun v14602eb-Insider

### 插件版本

build 40 git 1e15fda

**Comment by ybw0014** [comment]
已暂时修复
